# docker-composeのバージョンを指定
version: "3.9"

# db(MySQL),app(Django)のコンテナを作成
services:
  db:
    # コンテナ名をmysqlに設定
    # container_name: MySQL
    # MySQLのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: Docker/MySQL/Dockerfile
    # M1チップでも動くように
    # Intel Macの場合あってもなくても動く
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # DBのボリュームを指定
    # ローカルの/data/dbをコンテナの/var/lib/mysqlにマウントする
    volumes:
      - ./mysql_data:/var/lib/mysql
    # # コンテナ内の環境変数を.envを使って設定する場合
    env_file:
      - .env
    # DBのコンテナのヘルスチェックを行う
    # mysqladmin(MySQLサーバーの管理を行うクライアントを使ってDBコンテナ自身(127.0.0.1)にpingを送ってヘルスチェックを行う
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      # ヘルスチェックのインターバルは10秒
      interval: 10s
      # タイムアウト時間は10秒
      timeout: 10s
      # リトライ回数は3回
      retries: 3
      # ヘルスチェックが失敗しても無視する時間は30秒
      start_period: 30s

  app:
    # コンテナ名をdjangoに設定
    # container_name: Django
    # DjangoのDockerfileをビルドする
    build: 
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: Docker/Django/Dockerfile
    # ボリュームを指定
    # ローカルのカレントディレクトリをコンテナの/codeにマウントする
    # ローカルの/staticをコンテナの/staticにマウントする
    volumes:
      - ./Mondai:/code
      - ./static:/static
    # ローカルの8000番ポートとコンテナの8000番ポートをつなぐ
    ports:
      - "8000:8000"
    # コマンドを実行
    # python manage.py collectstaticで静的ファイルをstaticファイルに集める
    # --noinputで入力を省略する（collectstaticはそのまま実行すると、yes,noを聞かれる）
    # python manage.py runserver 0.0.0.0:8000でappコンテナをupした時にサーバが起動
    # command:  bash -c "python manage.py makemigrations && \
    #           python manage.py migrate && \
    #           python manage.py collectstatic --noinput && \
    #           python manage.py runserver 0.0.0.0:8000"
    # Nginxを使う場合は、以下のcommandに差し替える
    command: bash -c "python manage.py makemigrations && 
            python manage.py migrate && 
            python manage.py collectstatic --noinput && 
            uwsgi --socket :8000 --module Mondai_project.wsgi --py-autoreload 1 --log-master" #ログを表示せずに保存するなら--logto /tmp/mylog.log追記
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
    # 先にdbを起動してからappを起動する
    depends_on:
      db:
        # dbのヘルスチェックが終わってからappを起動させる
        condition: service_healthy
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
    links:
      - db
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    
# Nginxを使う場合は以下コメント外す。
  web:
  # コンテナ名をnginxに指定
  # container_name: Nginx
    # NginxのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: Docker/Nginx/Dockerfile
    # ボリュームを指定
    # ローカルの/staticをコンテナの/staticにマウントする
    volumes:
      - ./Docker/Nginx/conf:/etc/nginx/conf.d
      - ./Docker/Nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    # ローカルの80番ボートをコンテナの80番ポートとつなぐ
    ports:
      - "80:80"
    # 先にappを起動してからwebを起動する
    depends_on:
      - app

volumes:
  mysql_data:
  static:
